name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: alokbhateshwar
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#7845ab
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=blue
            dist/github-contribution-grid-snake-ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push Snake Files to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake animation"
          add: "dist/*"
